name: deploy_staging

on:
  push:
    tags:
      - 'v*-staging'

jobs:
  deploy:
    uses: ./.github/workflows/terraform_apply.yml
    with:
      environment: staging
      working_directory: environments/staging

