name: feature_ci

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'environments/**'
      - 'modules/**'
      - '*.tf'
      - '**/*.tf'

jobs:
  ci:
    uses: ./.github/workflows/terraform_plan.yml
    secrets: inherit
    with:
      environment: dev
      working_directory: environments/dev